apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rsn
  name: rsn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsn
  template:
    metadata:
      labels:
        app: rsn
    spec:
      containers:
        - name: rsn
          image: bkantor/rsn-webapp:0.1
          ports:
            - containerPort: 80
      restartPolicy: Always
